#! /bin/sh

~/.config/bspwm/startup.sh &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_motion_interval 7
bspc config focus_follows_pointer true
bspc config border_width 0
bspc config window_gap 12
bspc config borderless_monocle true

bspc rule -a feh state=floating
bspc rule -a mpv state=floating rectangle=1280x720+1080+360
bspc rule -a discord state=pseudo_tiled rectangle=1920x1080+0+0
