#!/usr/bin/bash

~/.config/bspwm/scripts/startup.sh &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config pointer_motion_interval 7
bspc config focus_follows_pointer true
bspc config border_width 0
bspc config window_gap 12

bspc rule -a feh state=floating
bspc rule -a mpv state=floating
