alias ls="eza -1F --sort=type --color=always --icons=always"
alias la="eza -1AF --sort=type --color=always --icons=always"
alias ld="eza -1DF --sort=type --color=always --icons=always"
alias ll="eza -AlF --sort=type --git --color=always --icons=always"
alias tree="eza -T"
alias lf="lfcd"
alias nv="nvim"
alias dnv="doas nvim"

alias p="pacman"
alias dp="doas pacman"
alias dps="doas pacman -S"
alias dpr="doas pacman -Rns"
alias dpu="doas pacman -Syu"
alias apu="doas pacman -Syu && flatpak update"
alias psi="pacman -Si"
alias y="yay"
alias fpu="flatpak update"
alias fpi="flatpak install --app"

alias ga="git add"
alias gb="git branch"
alias gc="git checkout"
alias gcm="git commit -m"
alias gd="git diff"
alias gl="git log"
alias gp="git push"
alias gr="git rm"
alias gs="git status"
