format="""\
$os\
[](fg:cyan bg:blue)\
$username\
[](fg:blue bg:green)\
$directory\
[](fg:green bg:purple)\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
[ ](fg:purple)\
"""

[os]
disabled = false
format = "[ $symbol ]($style)"
style = "fg:black bg:cyan"

[os.symbols]
Macos = " "

[username]
show_always = true
format = "[ $user ]($style)"
style_user = "fg:black bg:blue"

[hostname]
ssh_only = false
format = "[@$hostname ](fg:black bg:blue)"

[directory]
format = "[ $path ]($style)"
style = "fg:black bg:green"

[git_branch]
format = "[ $symbol$branch ]($style)"
style = "fg:black bg:purple"

[git_commit]
format = '[\($hash$tag\) ]($style)'
style = "fg:black bg:purple"

[git_status]
format = '[\[$all_status$ahead_behind\]](fg:black bg:purple)'
deleted="×"

[git_metrics]
added_style = "fg:bold black bg:purple"
deleted_style = "fg:bold black bg:purple"
format = '[ +$added]($added_style)[ -$deleted ]($deleted_style)'
disabled = false

[character]
success_symbol = "[  ](fg:green bg:black)"
error_symbol = "[  ](fg:red bg:black)"
