require('core.set')
require('core.map')
require('core.lsp.cmp')
require('core.lsp.luasnip')
require('core.lsp.mason')
require('core.lsp.lspconfig')
require('core.lsp.treesitter')
require('core.packer')
require('core.dashboard')
require('core.telescope')
require('core.themes.kanagawa')

--require('core.filetree')
